#!/bin/bash

# GitHub Release创建指导脚本
echo "=== GitHub Release 创建指导 ==="
echo ""
echo "✅ 代码已成功推送到GitHub！"
echo ""
echo "现在请手动创建GitHub Release："
echo ""
echo "步骤1：访问Release页面"
echo "打开：https://github.com/bubble-wu/table-column-resizer/releases"
echo ""
echo "步骤2：创建新Release"
echo "点击 'Create a new release' 按钮"
echo ""
echo "步骤3：填写Release信息"
echo "标签版本（Tag version）: 1.0.0"
echo "目标（Target）: main"
echo "Release标题: Table Column Resizer v1.0.0"
echo "描述:"
echo "Initial release with preview mode table column resizing support."
echo ""
echo "步骤4：上传文件（重要！）"
echo "点击下方区域，选择并上传以下文件："
echo "- main.js"
echo "- manifest.json" 
echo "- styles.css"
echo "⚠️  注意：这些文件必须单独上传，不能打包成zip！"
echo ""
echo "步骤5：发布"
echo "点击 'Publish release' 按钮"
echo ""
echo "=== 验证Release ==="
echo "完成后，访问：https://github.com/bubble-wu/table-column-resizer/releases/tag/1.0.0"
echo "确认所有文件都已正确上传"
echo ""
echo "=== 下一步 ==="
echo "完成Release创建后，你就可以："
echo "1. 关闭当前的PR #8508"
echo "2. 创建新的PR，使用正确的模板格式"
echo ""
read -p "完成GitHub Release创建后，按回车继续..."

echo ""
echo "✅ 太棒了！现在你可以重新提交PR到Obsidian社区了。"
echo "记得使用正确的PR模板格式！"